apiVersion: skaffold/v3
kind: Config

build:
  artifacts:
    - image: balie-server
      context: .
      docker:
        dockerfile: balie-server/Dockerfile
    - image: yivi-server
      context: yivi-server
  local:
    useBuildkit: true
    concurrency: 0
    push: true

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: yivi-balie
        namespace: "yivi-balie"
        chartPath: helm/yivi-balie
        createNamespace: true
        setValueTemplates:
          imageBalieServer: "{{.IMAGE_FULLY_QUALIFIED_balie_server}}"
          imageYiviServer: "{{.IMAGE_FULLY_QUALIFIED_yivi_server}}"

profiles:
  - name: prod
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - helm/yivi-balie/values-prod.yaml
      - op: add
        path: /deploy/helm/releases/0/namespace
        value: yivi-balie
